### ISSUE TITLE
Missing route configuration in certain parts

### ISSUE THREAD

**Issue by Max101** [witrin/TypoGento#31]
Hi!
I am not sure wether I should post this here and if it is a generic problem but nonetheless here it is:

I have the latest Typo3 4.5 and Magento 1.7 latest. All is configured and works pretty well; however there are some things that do not. For example:

When opening the cart page and clicking on "Delete item" I get a Typo3 error 

"Page Not Found
Reason: Segment "checkout" was not a keyword for a postVarSet as expected!"

The url being called is "http://example.com/index.php?id=461&tx_typogento%5Broute%5D=checkout&tx_typogento%5Bcontroller%5D=cart&tx_typogento%5Baction%5D=delete&tx_typogento%5Bid%5D=83&tx_typogento%5Buenc%5D=aHR0cDovL2FnZW5kYTIuYWdlbmRhLnNpL2NoZWNrb3V0L2NhcnQvaW5kZXgvPw%2C%2C&tx_typogento%5BSID%5D=gric3fqtcekr65d1jatc0sldlfv624ki"

This is then redirected to http://example.com/checkout/cart/index/?/.

Now, I think this could be a missing route configuration but I am not sure on how to fix this.
Help would be much appreciated.
Many thanks!

**Comment by witrin** [comment]
I migrate currently TypoGento to Extbase and TYPO3 6.0. Unfortunately I've not the time to support the previous versions, but I had fixed (unreleased) some minor bugs before the migration. 

I also had changed the generic routes setup, which contains foolishly some bugs. The `Page not found` errors are always caused by a misconfiguration of the dispatch routing. You could try an previous version of the [generic routes setup](https://gist.github.com/3220650/c860762a60455d6f480eb73fa08c2fea58ba8cc8). I'll try within the next days to release a hopefully complete working generic route setup. Please be patient.

With the upcoming release for TYPO3 6.0 you will get an easy to use single-page setup (including Ajax support) and a debug log for the routing, so you can better see how the URLs are mapped between TYPO3 and Magento. I also had fixed the redirect problems (caused by the base64 encoded parameter 'uenc') in the upcoming release.

**Comment by Max101** [comment]
Many thanks! I'll wait for that and hopefully they also release a much more stable version of Typo3 6.0 :)
Good luck!
